package com.github.cashpath.model.dto;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Player asset that generates daily cash flow")
public record AssetDTO(

        @Schema(
                description = "Asset name",
                example = "Apartment for rent"
        )
        String name,

        @Schema(
                description = "Daily income generated by the asset",
                example = "120.50"
        )
        double dailyCashFlow
) {
}
